In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load the dataset 
df = pd.read_csv('CLEAN_DATA/2015-2020_percountry_peryear.csv')

In [3]:
display(df)

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,country,countryname,oecdmember,eumember,edate,date,party,...,rile,planeco,markeco,welfare,intpeace,datasetversion,id_perm,Gini coefficient,stance_positivity_score,Success
0,0,0,129,11,Sweden,10,10.0,2018-09-09,201809,11110,...,-15.966,0.000,0.168,18.487,2.353,2023a,VXLO39,0.299742,63.025,1
1,1,1,130,11,Sweden,10,10.0,2018-09-09,201809,11220,...,-40.701,1.067,0.000,37.652,3.506,2023a,IJRAPK,0.299742,53.201,1
2,2,2,131,11,Sweden,10,10.0,2018-09-09,201809,11320,...,-20.000,0.645,0.000,22.258,0.645,2023a,GV4CQK,0.299742,68.064,1
3,3,3,132,11,Sweden,10,10.0,2018-09-09,201809,11420,...,-1.144,1.144,2.778,16.503,0.000,2023a,7O4BQ2,0.299742,50.814,1
4,4,4,133,11,Sweden,10,10.0,2018-09-09,201809,11520,...,-12.712,2.542,0.000,34.746,0.000,2023a,4FL7IT,0.299742,55.086,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,449,449,4665,98,Ukraine,0,0.0,2019-07-21,201907,98350,...,-4.717,1.887,1.887,13.208,12.264,2023a,ZHUFI7,0.266195,62.262,1
450,450,450,4666,98,Ukraine,0,0.0,2019-07-21,201907,98440,...,2.128,8.511,3.191,4.255,0.000,2023a,RB6257,0.266195,62.767,1
451,451,451,4667,98,Ukraine,0,0.0,2019-07-21,201907,98450,...,22.892,3.614,2.410,3.614,9.639,2023a,JT5WL6,0.266195,48.192,1
452,452,452,4668,98,Ukraine,0,0.0,2019-07-21,201907,98617,...,-23.377,5.195,3.896,15.584,5.195,2023a,W96R9B,0.266195,70.129,1
453,453,453,4669,98,Ukraine,0,0.0,2019-07-21,201907,98631,...,25.000,3.409,1.136,4.545,5.682,2023a,JC6ADL,0.266195,77.272,1

In [4]:
df['RILE_stance_score_interaction'] = df['rile'] * df['stance_positivity_score']

In [5]:
display(df['RILE_stance_score_interaction'])

0     -1006.257150
1     -2165.333901
2     -1361.280000
3       -58.131216
4      -700.253232
          ...
449    -293.689854
450     133.568176
451    1103.211264
452   -1639.405633
453    1931.800000
Name: RILE_stance_score_interaction, Length: 454, dtype: float64

In [ ]:
#save as csv (ps = positivity score)
df.to_csv("CLEAN_DATA/2015-2020_percountry_peryear_final.csv")